name: "CI checks"
on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - main
jobs:
  checks:
    name: code verifications
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - run: npm install

      - name: Check lint
        shell: bash
        run: |
          npm run lint

      - name: Check prettier formatting
        shell: bash
        run: |
          npm run check-format

      - name: Run build
        shell: bash
        run: |
          npm run build
